name: Render Quarto Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false  # Change to true if you want to push the image
          tags: quarto-render
      - name: Commit HTML output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: 
          # Set up Git
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # Check if the output file exists and commit if it does
          git add *.html
          git commit -m "Update rendered HTML output" || echo "No changes to commit"
          git push origin main
