name: Render Quarto Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build docker images
        run: docker build -t local < ./Dockerfile
      - name: Run image
        run: docker run local
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: render report
