name: Render Quarto Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build docker images
        run: docker build -t local .
      - name: Run image
        run: docker run local "quarto geocoder_evaluation.qmd"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: render report
